package compiler.fileanalyzer;

/**
 * User: Javier Isoldi
 * Date: 3/15/13
 * Time: 11:30 AM
 */
public enum TokenType {
    IDENTIFIER,
    COMMENT,
    NUMERICAL_CONSTANT,
    CHAR_CHAIN,
    ARITHMETIC_OPERATOR,
    ASSIGNATION_OPERATOR,
    INCREMENTAL_OPERATOR,
    ASSOCIATIVE_OPERATOR,
    LOGIC_OPERATOR,
    NEG_OPERATOR,
    POSITIVE_OPERATOR,
    SIZE_OF_OPERATOR,
    LOGIC_NEG_OPERATOR,
    COMMA_OPERATOR,
    BLOCK,
    SQUARE_BRACKET_BLOCK,
    KEY_WORD,
    BASIC_TYPE,
    SENTENCE_END,
    OPENING_BRACKET,
    CLOSING_BRACKET,
    PRE_PROCESSOR_INSTRUCTION,
    FILE_TO_INCLUDE,
    ASTERISK,
    POINT_OPERATOR, ADDRESS_OPERATOR,
    CASE_OPERATOR

}
